version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      minor:
        update-types:
          - "patch"
          - "minor"
      major:
        update-types:
          - "major"
