name: Run tests and lint

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install tooling
        run: |
          rustup component add rustfmt
          rustup component add clippy
          cargo install cargo-audit
      - name: Rustfmt
        run: cargo fmt -- --check
      - name: Clippy
        run: cargo clippy --all-targets --all-features
      - name: Package Audit
        run: |
            mkdir -p ~/.cargo
            cp .cargo/audit.toml ~/.cargo/audit.toml
            cargo audit

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download GeoDB
        run: |
          echo "::add-mask::${GEOLITE_API_KEY}"
          if [ "${GEOLITE_API_KEY}" == "" ]; then
            echo "GEOLITE_API_KEY env var required"
            exit 1
          fi
          URL="https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country&license_key=${GEOLITE_API_KEY}&suffix=tar.gz"
          curl "$URL" --output geolite.tar.gz
          tar --strip-components=1 --wildcards -zxvf geolite.tar.gz -- '*/GeoLite2-Country.mmdb'
      - name: Build
        run: cargo build --release
      - name: Test
        run: cargo test --release
